# TensorFlow Basics

In [2]:
import tensorflow as tf

In [3]:
# Make sure you are using 1.3 for exact sytnax matching!
print(tf.__version__)

1.11.0


## Tensors

In [4]:
hello = tf.constant('Hello')

In [5]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [6]:
world = tf.constant('World')

In [7]:
result = hello + world

In [8]:
result

<tf.Tensor 'add:0' shape=() dtype=string>

In [9]:
type(result)

tensorflow.python.framework.ops.Tensor

In [12]:
with tf.Session() as sess:
    result = sess.run(hello+world)

In [11]:
result

b'HelloWorld'

** Computations **

In [16]:
tensor_1 = tf.constant(1)
tensor_2 = tf.constant(2)

In [17]:
type(tensor_1)

tensorflow.python.framework.ops.Tensor

In [20]:
tensor_1 + tensor_2

<tf.Tensor 'add_5:0' shape=() dtype=int32>

In [21]:
sess

In [22]:
sess.close()

## Operations

In [23]:
const = tf.constant(10)

In [25]:
fill_mat = tf.fill((4,4),10)

In [26]:
myzeros = tf.zeros((4,4))

In [27]:
myones = tf.ones((4,4))

In [28]:
myrandn = tf.random_normal((4,4),mean=0,stddev=0.5)

In [29]:
myrandu = tf.random_uniform((4,4),minval=0,maxval=1)

In [30]:
my_ops = [const,fill_mat,myzeros,myones,myrandn,myrandu]

## Interactive Session

Useful for Notebook Sessions

In [31]:
# Only run this cell once!
sess = tf.InteractiveSession()

In [34]:
for op in my_ops:
    print(op.eval())
    print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[-0.11283274 -0.9121977  -0.6732429   1.341617  ]
 [-1.0806577   0.24670143 -0.3794133   0.52815515]
 [-0.7497048  -0.24669911 -0.95284414 -0.6767401 ]
 [ 0.62462634 -0.77299666 -0.05295547 -0.97569823]]


[[0.24411464 0.93378615 0.47851706 0.09849429]
 [0.19371474 0.1566714  0.6314746  0.29436505]
 [0.23685324 0.06665194 0.5236002  0.7306293 ]
 [0.10136473 0.9399339  0.92358804 0.21612835]]




## Matrix Multiplication

In [35]:
a = tf.constant([ [1,2],
                  [3,4] ])

In [36]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [37]:
b = tf.constant([[10],[100]])

In [38]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [39]:
result = tf.matmul(a,b)

In [40]:
result.eval()

array([[210],
       [430]], dtype=int32)